### ISSUE TITLE
Create Homepage and Navigation

### ISSUE THREAD

**Issue by fadlystwn** [ririn-caterin/pet-store#1]
Feature Request: Create Home Page with Navigation Menu

Hi @ririn-caterin,

Could you please create the home page and include a navigation menu? The navigation menu should have the following items:

- Home
- Shop
- Services
- Contact

Branching Instructions:
When creating the branch, please follow this naming convention:
feature-create-homepage-navigation

To create and check out the branch(Please create under branch main):
`git checkout -b feature-create-homepage-navigation`

Let me know if you need further clarification or additional details. Thank you!

**Comment by ririn-caterin** [comment]
Hi @fadlystwn,

I have completed the home page along with the navigation menu as requested. The navigation menu includes the following items:

Home
Shop
Services
Contact

The changes have been pushed to the branch feature-create-homepage-navigation. Please feel free to review and let me know if you have any feedback or need further adjustments.

Thank you!
