### ISSUE TITLE
Feature Request: Add Product to Cart

### ISSUE THREAD

**Issue by fadlystwn** [ririn-caterin/pet-store#10]
Implement the functionality to allow users to add products to a shopping cart
 
 - Add React context Reducer
 - Update the cart icon/header with the current item count in real time.
 -  Persist the cart state in localStorage

**Comment by ririn-caterin** [comment]
Hello mas @fadlystwn,
I'm done implementing that functionality based on your request. Kindly check my code and let me know if you have any feedback!
