### ISSUE TITLE
Implement Login Authentication

### ISSUE THREAD

**Issue by fadlystwn** [ririn-caterin/pet-store#2]
Hi @ririn-caterin,

Could you please implement login authentication functionality for the project? This feature should include:

**Login Form**: A simple form with fields for username/email and password.
**Validation**: Ensure basic validation for required fields.
**API Integration**: Connect the form to the authentication API for login validation.
**Error Handling**: Display appropriate error messages for invalid login attempts.

Branching Instructions
When creating the branch, please follow this naming convention:
feature-create-login-auth

To create and check out the branch:
`git checkout -b feature-create-login-auth` 
Let me know if you need additional details or clarification. Thank you!

**Comment by ririn-caterin** [comment]
Hi  @fadlystwn ,

I’ve implemented the login authentication functionality. For now, it uses Google Account login as the authentication method.
I have pushed the implementation to the branch named `feature-create-login-auth`
