### ISSUE TITLE
Add Product Details Page

### ISSUE THREAD

**Issue by fadlystwn** [ririn-caterin/pet-store#9]
We need to implement a detailed product page where users can view in-depth information about a specific product.

Key Features:

- Display product details fetched from the backend.
- Add buttons for actions like "Buy Now" or "Add to Cart."

**Comment by ririn-caterin** [comment]
Hi mas @fadlystwn ,
I've already created the product detail page and added an "Add to Cart" button to allow users to order the product.
Please review my code, and let me know if you have any feedback!
